export const FETCH_CONCERT = 'FETCH_CONCERT'
export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'
export const CRAWL_FIND = 'CRAWL_FIND'
export const FETCH_LIKED_LIST = 'FETCH_LIKED_LIST'
export const FETCH_LIKED_OR_NOT = 'FETCH_LIKED_OR_NOT'
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_REPLY_LIST = 'FETCH_REPLY_LIST'

export const FETCH_DECIDE_OR_NOT = 'FETCH_DECIDE_OR_NOT'
export const FETCH_TASTE = 'FETCH_TASTE'

export const FETCH_USER_NAME = 'FETCH_USER_NAME'

export const FETCH_CONCERT_REQUEST_LIST = 'FETCH_CONCERT_REQUEST_LIST'
export const FETCH_CONCERT_REQUEST = 'FETCH_CONCERT_REQUEST'

export const FETCH_MY_REQUEST_LIST = 'FETCH_MY_REQUEST_LIST'

export const FETCH_BOOKED_OR_NOT = 'FETCH_BOOKED_OR_NOT'
export const FETCH_BOOKED_LIST = 'FETCH_BOOKED_LIST'
export const FETCH_BOOKED_CONCERT = 'FETCH_BOOKED_CONCERT'

export const FETCH_SEARCHED_RESULTS = 'FETCH_SEARCHED_RESULTS'
export const FETCH_SEARCHED_ARTISTS = 'FETCH_SEARCHED_ARTISTS'